/**
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, 
 * the first 10 * terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do 
 * not exceed four million, find the sum of the even-valued terms.
 */

#include <stdlib.h>
#include <stdio.h>

int fibSum(int * sum, int x, int y){
    if (y > 4000000){
        *sum += !(x % 2) ? x : 0;
        return *sum;
    } else {
        *sum += !(x % 2) ? x : 0;
        return fibSum(sum, y, x + y);
    }
}

int main(){

    int sum = 0;
    int x = 1;
    int y = 2;

    printf("%d\n", fibSum(&sum, x, y));
    return 0;
}
